// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: MorseSender-v0.4

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Send_Screen
void ui_Send_Screen_screen_init(void);
void ui_event_Send_Screen(lv_event_t * e);
void ui_event_SendButton(lv_event_t * e);
lv_obj_t * ui_Send_Screen;
lv_obj_t * ui_SendButton1;
lv_obj_t * ui_SendButton1Label;
lv_obj_t * ui_SendButton2;
lv_obj_t * ui_SendButton2Label;
lv_obj_t * ui_SendButton3;
lv_obj_t * ui_SendButton3Label;
lv_obj_t * ui_SendButton4;
lv_obj_t * ui_SendButton4Label;
lv_obj_t * ui_SendButton5;
lv_obj_t * ui_SendButton5Label;
lv_obj_t * ui_SendButton6;
lv_obj_t * ui_SendButton6Label;
lv_obj_t * ui_SendButton7;
lv_obj_t * ui_SendButton7Label;
lv_obj_t * ui_SendScreenButton;
lv_obj_t * ui_SendButtonLabel;
void ui_event_ConfigButton(lv_event_t * e);
lv_obj_t * ui_ConfigButton;
lv_obj_t * ui_ConfigButtonLabel;
void ui_event_KeyboardButton(lv_event_t * e);
lv_obj_t * ui_KeyboardButton;
lv_obj_t * ui_KeyboardButtonLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Config_Screen
void ui_Config_Screen_screen_init(void);
void ui_event_Config_Screen(lv_event_t * e);
lv_obj_t * ui_Config_Screen;
void ui_event_SendScreenButton2(lv_event_t * e);
lv_obj_t * ui_SendScreenButton2;
lv_obj_t * ui_SendScreenButtonLabel2;
lv_obj_t * ui_ConfigButton2;
lv_obj_t * ui_ConfigButtonLabel2;
void ui_event_KeyboardButton2(lv_event_t * e);
lv_obj_t * ui_KeyboardButton2;
lv_obj_t * ui_KeyboardButtonLabel2;
lv_obj_t * ui_SpeedDropdownLabel;
lv_obj_t * ui_ProgDropdownLabel;
lv_obj_t * ui_ProgramDropdown;
lv_obj_t * ui_SetButton;
lv_obj_t * ui_SetButtonLabel;
void ui_event_SpeedSlider(lv_event_t * e);
lv_obj_t * ui_SpeedSlider;
lv_obj_t * ui_SpeedValueLabel;
// CUSTOM VARIABLES
lv_obj_t * uic_SetButton;

// SCREEN: ui_Keyboard__Screen
void ui_Keyboard__Screen_screen_init(void);
void ui_event_Keyboard__Screen(lv_event_t * e);
lv_obj_t * ui_Keyboard__Screen;
void ui_event_SendScreenButton1(lv_event_t * e);
lv_obj_t * ui_SendScreenButton1;
lv_obj_t * ui_SendScreenButtonLabel1;
void ui_event_ConfigButton1(lv_event_t * e);
lv_obj_t * ui_ConfigButton1;
lv_obj_t * ui_ConfigButtonLabel1;
lv_obj_t * ui_KeyboardButton1;
lv_obj_t * ui_KeyboardButtonLabel1;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui_TextArea1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
// Implemented in ui.ino (extern "C") — called when a send button is tapped.
extern void onSendButton(int slot);
// Implemented in ui.ino (extern "C") — called when Stop button is tapped.
extern void onStopButton(void);
// Implemented in ui.ino (extern "C") — called when WPM slider changes.
extern void onSpeedSlider(int wpm);
// Implemented in ui.ino (extern "C") — Phase 4 keyboard flow.
extern void onSetButton(int slot);
extern void onKeyboardNavButton(void);
extern int  isKbdEditMode(void);
extern void onKeyboardScreenLoad(void);
extern void onKeyboardConfirm(const char *text);

void ui_event_SendButton(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_SHORT_CLICKED) return;

    lv_obj_t * target = lv_event_get_target(e);
    int slot = -1;
    if      (target == ui_SendButton1) slot = 0;
    else if (target == ui_SendButton2) slot = 1;
    else if (target == ui_SendButton3) slot = 2;
    else if (target == ui_SendButton4) slot = 3;
    else if (target == ui_SendButton5) slot = 4;
    else if (target == ui_SendButton6) slot = 5;
    else if (target == ui_SendButton7) slot = 6;

    if (slot >= 0) onSendButton(slot);
}

void ui_event_Send_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_state_modify(ui_SendScreenButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_ConfigButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_Config_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Config_Screen_screen_init);
    }
}

void ui_event_KeyboardButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        onKeyboardNavButton();   // one-shot send mode — not arriving via Config Set
        _ui_screen_change(&ui_Keyboard__Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Keyboard__Screen_screen_init);
    }
}

void ui_event_Config_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_state_modify(ui_ConfigButton2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_SendScreenButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_Send_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Send_Screen_screen_init);
    }
}

void ui_event_KeyboardButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        onKeyboardNavButton();   // one-shot send mode — not arriving via Config Set
        _ui_screen_change(&ui_Keyboard__Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Keyboard__Screen_screen_init);
    }
}

void ui_event_SpeedSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        int wpm = (int)lv_slider_get_value(ui_SpeedSlider);
        char buf[8];
        lv_snprintf(buf, sizeof(buf), "%d", wpm);
        lv_label_set_text(ui_SpeedValueLabel, buf);
        onSpeedSlider(wpm);
    }
}

void ui_event_SetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        int slot = (int)lv_dropdown_get_selected(ui_ProgramDropdown);
        onSetButton(slot);
        _ui_screen_change(&ui_Keyboard__Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0,
                          &ui_Keyboard__Screen_screen_init);
    }
}

void ui_event_StopButton(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_SHORT_CLICKED) {
        onStopButton();
    }
}

void ui_event_Keyboard__Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_state_modify(ui_KeyboardButton1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        onKeyboardScreenLoad();
    }
}

void ui_event_SendScreenButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_Send_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Send_Screen_screen_init);
    }
}

void ui_event_ConfigButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_Config_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Config_Screen_screen_init);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY) {
        _ui_keyboard_set_target(ui_Keyboard1, ui_TextArea1);
    }
    if(event_code == LV_EVENT_READY) {
        onKeyboardConfirm(lv_textarea_get_text(ui_TextArea1));
        // Edit mode returns to Config; send mode returns to Send screen.
        if(isKbdEditMode()) {
            _ui_screen_change(&ui_Config_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0,
                              &ui_Config_Screen_screen_init);
        } else {
            _ui_screen_change(&ui_Send_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0,
                              &ui_Send_Screen_screen_init);
        }
    }
    if(event_code == LV_EVENT_CANCEL) {
        // Cancel always returns to where we came from.
        if(isKbdEditMode()) {
            _ui_screen_change(&ui_Config_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0,
                              &ui_Config_Screen_screen_init);
        } else {
            _ui_screen_change(&ui_Send_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0,
                              &ui_Send_Screen_screen_init);
        }
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Send_Screen_screen_init();
    ui_Config_Screen_screen_init();
    ui_Keyboard__Screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Send_Screen);
}
