// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: MorseSender-v0.4

#ifndef _MORSESENDER_V0_4_UI_H
#define _MORSESENDER_V0_4_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Send_Screen
void ui_Send_Screen_screen_init(void);
void ui_event_Send_Screen(lv_event_t * e);
extern lv_obj_t * ui_Send_Screen;
extern lv_obj_t * ui_SendButton1;
extern lv_obj_t * ui_SendButton1Label;
extern lv_obj_t * ui_SendButton2;
extern lv_obj_t * ui_SendButton2Label;
extern lv_obj_t * ui_SendButton3;
extern lv_obj_t * ui_SendButton3Label;
extern lv_obj_t * ui_SendButton4;
extern lv_obj_t * ui_SendButton4Label;
extern lv_obj_t * ui_SendButton5;
extern lv_obj_t * ui_SendButton5Label;
extern lv_obj_t * ui_SendButton6;
extern lv_obj_t * ui_SendButton6Label;
extern lv_obj_t * ui_SendButton7;
extern lv_obj_t * ui_SendButton7Label;
extern lv_obj_t * ui_SendScreenButton;
extern lv_obj_t * ui_SendButtonLabel;
void ui_event_SendButton(lv_event_t * e);
void ui_event_StopButton(lv_event_t * e);
void ui_event_SetButton(lv_event_t * e);
void ui_event_ConfigButton(lv_event_t * e);
extern lv_obj_t * ui_ConfigButton;
extern lv_obj_t * ui_ConfigButtonLabel;
void ui_event_KeyboardButton(lv_event_t * e);
extern lv_obj_t * ui_KeyboardButton;
extern lv_obj_t * ui_KeyboardButtonLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Config_Screen
void ui_Config_Screen_screen_init(void);
void ui_event_Config_Screen(lv_event_t * e);
extern lv_obj_t * ui_Config_Screen;
void ui_event_SendScreenButton2(lv_event_t * e);
extern lv_obj_t * ui_SendScreenButton2;
extern lv_obj_t * ui_SendScreenButtonLabel2;
extern lv_obj_t * ui_ConfigButton2;
extern lv_obj_t * ui_ConfigButtonLabel2;
void ui_event_KeyboardButton2(lv_event_t * e);
extern lv_obj_t * ui_KeyboardButton2;
extern lv_obj_t * ui_KeyboardButtonLabel2;
extern lv_obj_t * ui_SpeedDropdownLabel;
extern lv_obj_t * ui_ProgDropdownLabel;
extern lv_obj_t * ui_ProgramDropdown;
extern lv_obj_t * ui_SetButton;
extern lv_obj_t * ui_SetButtonLabel;
void ui_event_SpeedSlider(lv_event_t * e);
extern lv_obj_t * ui_SpeedSlider;
extern lv_obj_t * ui_SpeedValueLabel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SetButton;

// SCREEN: ui_Keyboard__Screen
void ui_Keyboard__Screen_screen_init(void);
void ui_event_Keyboard__Screen(lv_event_t * e);
extern lv_obj_t * ui_Keyboard__Screen;
void ui_event_SendScreenButton1(lv_event_t * e);
extern lv_obj_t * ui_SendScreenButton1;
extern lv_obj_t * ui_SendScreenButtonLabel1;
void ui_event_ConfigButton1(lv_event_t * e);
extern lv_obj_t * ui_ConfigButton1;
extern lv_obj_t * ui_ConfigButtonLabel1;
extern lv_obj_t * ui_KeyboardButton1;
extern lv_obj_t * ui_KeyboardButtonLabel1;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_TextArea1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
