// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: MorseSender-v0.4

#include "ui.h"

void ui_Config_Screen_screen_init(void)
{
    ui_Config_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Config_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SendScreenButton2 = lv_button_create(ui_Config_Screen);
    lv_obj_set_width(ui_SendScreenButton2, 26);
    lv_obj_set_height(ui_SendScreenButton2, 50);
    lv_obj_set_x(ui_SendScreenButton2, -135);
    lv_obj_set_y(ui_SendScreenButton2, -82);
    lv_obj_set_align(ui_SendScreenButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendScreenButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SendScreenButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SendScreenButtonLabel2 = lv_label_create(ui_SendScreenButton2);
    lv_obj_set_width(ui_SendScreenButtonLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SendScreenButtonLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SendScreenButtonLabel2, 11);
    lv_obj_set_y(ui_SendScreenButtonLabel2, 26);
    lv_obj_set_align(ui_SendScreenButtonLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SendScreenButtonLabel2, "Send");
    lv_obj_set_style_transform_rotation(ui_SendScreenButtonLabel2, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButton2 = lv_button_create(ui_Config_Screen);
    lv_obj_set_width(ui_ConfigButton2, 26);
    lv_obj_set_height(ui_ConfigButton2, 50);
    lv_obj_set_x(ui_ConfigButton2, -135);
    lv_obj_set_y(ui_ConfigButton2, -20);
    lv_obj_set_align(ui_ConfigButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ConfigButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigButton2, lv_color_hex(0xFE0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButtonLabel2 = lv_label_create(ui_ConfigButton2);
    lv_obj_set_width(ui_ConfigButtonLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfigButtonLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConfigButtonLabel2, 11);
    lv_obj_set_y(ui_ConfigButtonLabel2, 26);
    lv_obj_set_align(ui_ConfigButtonLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfigButtonLabel2, "Config");
    lv_obj_set_style_text_color(ui_ConfigButtonLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfigButtonLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfigButtonLabel2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_ConfigButtonLabel2, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardButton2 = lv_button_create(ui_Config_Screen);
    lv_obj_set_width(ui_KeyboardButton2, 26);
    lv_obj_set_height(ui_KeyboardButton2, 80);
    lv_obj_set_x(ui_KeyboardButton2, -134);
    lv_obj_set_y(ui_KeyboardButton2, 54);
    lv_obj_set_align(ui_KeyboardButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_KeyboardButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KeyboardButtonLabel2 = lv_label_create(ui_KeyboardButton2);
    lv_obj_set_width(ui_KeyboardButtonLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KeyboardButtonLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KeyboardButtonLabel2, 20);
    lv_obj_set_y(ui_KeyboardButtonLabel2, 32);
    lv_obj_set_align(ui_KeyboardButtonLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KeyboardButtonLabel2, "Keyboard");
    lv_obj_set_style_text_font(ui_KeyboardButtonLabel2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_KeyboardButtonLabel2, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedDropdownLabel = lv_label_create(ui_Config_Screen);
    lv_obj_set_width(ui_SpeedDropdownLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedDropdownLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedDropdownLabel, -53);
    lv_obj_set_y(ui_SpeedDropdownLabel, -96);
    lv_obj_set_align(ui_SpeedDropdownLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedDropdownLabel, "Speed (WPM)");

    ui_ProgDropdownLabel = lv_label_create(ui_Config_Screen);
    lv_obj_set_width(ui_ProgDropdownLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProgDropdownLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProgDropdownLabel, -72);
    lv_obj_set_y(ui_ProgDropdownLabel, -34);
    lv_obj_set_align(ui_ProgDropdownLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProgDropdownLabel, "Program");

    ui_ProgramDropdown = lv_dropdown_create(ui_Config_Screen);
    lv_dropdown_set_options(ui_ProgramDropdown, "Button 1\nButton 2\nButton 3\nButton 4\nButton 5\nButton 6\nButton 7");
    lv_obj_set_width(ui_ProgramDropdown, 150);
    lv_obj_set_height(ui_ProgramDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProgramDropdown, -29);
    lv_obj_set_y(ui_ProgramDropdown, -8);
    lv_obj_set_align(ui_ProgramDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProgramDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_ProgramDropdown, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetButton = lv_button_create(ui_Config_Screen);
    lv_obj_set_width(ui_SetButton, 63);
    lv_obj_set_height(ui_SetButton, 33);
    lv_obj_set_x(ui_SetButton, -4);
    lv_obj_set_y(ui_SetButton, 44);
    lv_obj_set_align(ui_SetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetButton, lv_color_hex(0x0CFD03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetButtonLabel = lv_label_create(ui_SetButton);
    lv_obj_set_width(ui_SetButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SetButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetButtonLabel, "Set");
    lv_obj_set_style_text_color(ui_SetButtonLabel, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedSlider = lv_slider_create(ui_Config_Screen);
    lv_slider_set_range(ui_SpeedSlider, 5, 30);
    lv_slider_set_value(ui_SpeedSlider, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SpeedSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SpeedSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpeedSlider, 150);
    lv_obj_set_height(ui_SpeedSlider, 10);
    lv_obj_set_x(ui_SpeedSlider, -20);
    lv_obj_set_y(ui_SpeedSlider, -74);
    lv_obj_set_align(ui_SpeedSlider, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SpeedSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SpeedSlider,
                                                                                                  lv_obj_get_style_pad_right(ui_SpeedSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_SpeedValueLabel = lv_label_create(ui_Config_Screen);
    lv_obj_set_width(ui_SpeedValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedValueLabel, 92);
    lv_obj_set_y(ui_SpeedValueLabel, -75);
    lv_obj_set_align(ui_SpeedValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedValueLabel, "");

    lv_obj_add_event_cb(ui_SendScreenButton2, ui_event_SendScreenButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardButton2, ui_event_KeyboardButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SpeedSlider, ui_event_SpeedSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetButton, ui_event_SetButton, LV_EVENT_SHORT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Config_Screen, ui_event_Config_Screen, LV_EVENT_ALL, NULL);
    uic_SetButton = ui_SetButton;

}
