// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: MorseSender-v0.4

#include "ui.h"

void ui_Keyboard__Screen_screen_init(void)
{
    ui_Keyboard__Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Keyboard__Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SendScreenButton1 = lv_button_create(ui_Keyboard__Screen);
    lv_obj_set_width(ui_SendScreenButton1, 26);
    lv_obj_set_height(ui_SendScreenButton1, 50);
    lv_obj_set_x(ui_SendScreenButton1, -135);
    lv_obj_set_y(ui_SendScreenButton1, -82);
    lv_obj_set_align(ui_SendScreenButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendScreenButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SendScreenButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SendScreenButtonLabel1 = lv_label_create(ui_SendScreenButton1);
    lv_obj_set_width(ui_SendScreenButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SendScreenButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SendScreenButtonLabel1, 11);
    lv_obj_set_y(ui_SendScreenButtonLabel1, 26);
    lv_obj_set_align(ui_SendScreenButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SendScreenButtonLabel1, "Send");
    lv_obj_set_style_transform_rotation(ui_SendScreenButtonLabel1, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButton1 = lv_button_create(ui_Keyboard__Screen);
    lv_obj_set_width(ui_ConfigButton1, 26);
    lv_obj_set_height(ui_ConfigButton1, 50);
    lv_obj_set_x(ui_ConfigButton1, -135);
    lv_obj_set_y(ui_ConfigButton1, -20);
    lv_obj_set_align(ui_ConfigButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ConfigButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigButton1, lv_color_hex(0xFE0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButtonLabel1 = lv_label_create(ui_ConfigButton1);
    lv_obj_set_width(ui_ConfigButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfigButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConfigButtonLabel1, 11);
    lv_obj_set_y(ui_ConfigButtonLabel1, 26);
    lv_obj_set_align(ui_ConfigButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfigButtonLabel1, "Config");
    lv_obj_set_style_text_color(ui_ConfigButtonLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfigButtonLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfigButtonLabel1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_ConfigButtonLabel1, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardButton1 = lv_button_create(ui_Keyboard__Screen);
    lv_obj_set_width(ui_KeyboardButton1, 26);
    lv_obj_set_height(ui_KeyboardButton1, 80);
    lv_obj_set_x(ui_KeyboardButton1, -134);
    lv_obj_set_y(ui_KeyboardButton1, 54);
    lv_obj_set_align(ui_KeyboardButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_KeyboardButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KeyboardButtonLabel1 = lv_label_create(ui_KeyboardButton1);
    lv_obj_set_width(ui_KeyboardButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KeyboardButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KeyboardButtonLabel1, 20);
    lv_obj_set_y(ui_KeyboardButtonLabel1, 32);
    lv_obj_set_align(ui_KeyboardButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KeyboardButtonLabel1, "Keyboard");
    lv_obj_set_style_text_font(ui_KeyboardButtonLabel1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_KeyboardButtonLabel1, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Keyboard__Screen);
    lv_obj_set_width(ui_Keyboard1, 264);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 21);
    lv_obj_set_y(ui_Keyboard1, 26);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_TextArea1 = lv_textarea_create(ui_Keyboard__Screen);
    lv_obj_set_width(ui_TextArea1, 257);
    lv_obj_set_height(ui_TextArea1, 70);
    lv_obj_set_x(ui_TextArea1, 20);
    lv_obj_set_y(ui_TextArea1, -74);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    lv_obj_add_event_cb(ui_SendScreenButton1, ui_event_SendScreenButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConfigButton1, ui_event_ConfigButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard__Screen, ui_event_Keyboard__Screen, LV_EVENT_ALL, NULL);

}
