// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: MorseSender-v0.4

#include "ui.h"

void ui_Send_Screen_screen_init(void)
{
    ui_Send_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Send_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SendButton1 = lv_button_create(ui_Send_Screen);
    lv_obj_set_width(ui_SendButton1, 258);
    lv_obj_set_height(ui_SendButton1, 23);
    lv_obj_set_x(ui_SendButton1, 20);
    lv_obj_set_y(ui_SendButton1, -98);
    lv_obj_set_align(ui_SendButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SendButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SendButton1, lv_color_hex(0x1D683B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButton1Label = lv_label_create(ui_SendButton1);
    lv_obj_set_width(ui_SendButton1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SendButton1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SendButton1Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SendButton1Label, "SendButton1");
    lv_obj_set_style_text_font(ui_SendButton1Label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButton2 = lv_button_create(ui_Send_Screen);
    lv_obj_set_width(ui_SendButton2, 258);
    lv_obj_set_height(ui_SendButton2, 23);
    lv_obj_set_x(ui_SendButton2, 20);
    lv_obj_set_y(ui_SendButton2, -68);
    lv_obj_set_align(ui_SendButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SendButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SendButton2, lv_color_hex(0x1D683B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButton2Label = lv_label_create(ui_SendButton2);
    lv_obj_set_width(ui_SendButton2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SendButton2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SendButton2Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SendButton2Label, "SendButton2");
    lv_obj_set_style_text_font(ui_SendButton2Label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButton3 = lv_button_create(ui_Send_Screen);
    lv_obj_set_width(ui_SendButton3, 258);
    lv_obj_set_height(ui_SendButton3, 23);
    lv_obj_set_x(ui_SendButton3, 20);
    lv_obj_set_y(ui_SendButton3, -38);
    lv_obj_set_align(ui_SendButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SendButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SendButton3, lv_color_hex(0x1D683B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButton3Label = lv_label_create(ui_SendButton3);
    lv_obj_set_width(ui_SendButton3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SendButton3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SendButton3Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SendButton3Label, "SendButton3");
    lv_obj_set_style_text_font(ui_SendButton3Label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButton4 = lv_button_create(ui_Send_Screen);
    lv_obj_set_width(ui_SendButton4, 258);
    lv_obj_set_height(ui_SendButton4, 23);
    lv_obj_set_x(ui_SendButton4, 20);
    lv_obj_set_y(ui_SendButton4, -8);
    lv_obj_set_align(ui_SendButton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SendButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SendButton4, lv_color_hex(0x1D683B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendButton4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButton4Label = lv_label_create(ui_SendButton4);
    lv_obj_set_width(ui_SendButton4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SendButton4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SendButton4Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SendButton4Label, "SendButton4");
    lv_obj_set_style_text_font(ui_SendButton4Label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButton5 = lv_button_create(ui_Send_Screen);
    lv_obj_set_width(ui_SendButton5, 258);
    lv_obj_set_height(ui_SendButton5, 23);
    lv_obj_set_x(ui_SendButton5, 20);
    lv_obj_set_y(ui_SendButton5, 22);
    lv_obj_set_align(ui_SendButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SendButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SendButton5, lv_color_hex(0x1D683B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButton5Label = lv_label_create(ui_SendButton5);
    lv_obj_set_width(ui_SendButton5Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SendButton5Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SendButton5Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SendButton5Label, "SendButton5");
    lv_obj_set_style_text_font(ui_SendButton5Label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButton6 = lv_button_create(ui_Send_Screen);
    lv_obj_set_width(ui_SendButton6, 258);
    lv_obj_set_height(ui_SendButton6, 23);
    lv_obj_set_x(ui_SendButton6, 20);
    lv_obj_set_y(ui_SendButton6, 52);
    lv_obj_set_align(ui_SendButton6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SendButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SendButton6, lv_color_hex(0x1D683B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendButton6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButton6Label = lv_label_create(ui_SendButton6);
    lv_obj_set_width(ui_SendButton6Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SendButton6Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SendButton6Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SendButton6Label, "SendButton6");
    lv_obj_set_style_text_font(ui_SendButton6Label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButton7 = lv_button_create(ui_Send_Screen);
    lv_obj_set_width(ui_SendButton7, 258);
    lv_obj_set_height(ui_SendButton7, 23);
    lv_obj_set_x(ui_SendButton7, 20);
    lv_obj_set_y(ui_SendButton7, 82);
    lv_obj_set_align(ui_SendButton7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendButton7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SendButton7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SendButton7, lv_color_hex(0x1D683B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendButton7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButton7Label = lv_label_create(ui_SendButton7);
    lv_obj_set_width(ui_SendButton7Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SendButton7Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SendButton7Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SendButton7Label, "SendButton7");
    lv_obj_set_style_text_font(ui_SendButton7Label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendScreenButton = lv_button_create(ui_Send_Screen);
    lv_obj_set_width(ui_SendScreenButton, 26);
    lv_obj_set_height(ui_SendScreenButton, 50);
    lv_obj_set_x(ui_SendScreenButton, -135);
    lv_obj_set_y(ui_SendScreenButton, -82);
    lv_obj_set_align(ui_SendScreenButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendScreenButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SendScreenButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SendButtonLabel = lv_label_create(ui_SendScreenButton);
    lv_obj_set_width(ui_SendButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SendButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SendButtonLabel, 11);
    lv_obj_set_y(ui_SendButtonLabel, 26);
    lv_obj_set_align(ui_SendButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SendButtonLabel, "Send");
    lv_obj_set_style_transform_rotation(ui_SendButtonLabel, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButton = lv_button_create(ui_Send_Screen);
    lv_obj_set_width(ui_ConfigButton, 26);
    lv_obj_set_height(ui_ConfigButton, 50);
    lv_obj_set_x(ui_ConfigButton, -135);
    lv_obj_set_y(ui_ConfigButton, -20);
    lv_obj_set_align(ui_ConfigButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ConfigButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigButton, lv_color_hex(0xFE0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigButtonLabel = lv_label_create(ui_ConfigButton);
    lv_obj_set_width(ui_ConfigButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfigButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConfigButtonLabel, 11);
    lv_obj_set_y(ui_ConfigButtonLabel, 26);
    lv_obj_set_align(ui_ConfigButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfigButtonLabel, "Config");
    lv_obj_set_style_text_color(ui_ConfigButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfigButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfigButtonLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_ConfigButtonLabel, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardButton = lv_button_create(ui_Send_Screen);
    lv_obj_set_width(ui_KeyboardButton, 26);
    lv_obj_set_height(ui_KeyboardButton, 80);
    lv_obj_set_x(ui_KeyboardButton, -134);
    lv_obj_set_y(ui_KeyboardButton, 54);
    lv_obj_set_align(ui_KeyboardButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_KeyboardButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KeyboardButtonLabel = lv_label_create(ui_KeyboardButton);
    lv_obj_set_width(ui_KeyboardButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KeyboardButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KeyboardButtonLabel, 20);
    lv_obj_set_y(ui_KeyboardButtonLabel, 32);
    lv_obj_set_align(ui_KeyboardButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KeyboardButtonLabel, "Keyboard");
    lv_obj_set_style_text_font(ui_KeyboardButtonLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_KeyboardButtonLabel, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SendScreenButton, ui_event_StopButton, LV_EVENT_SHORT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SendButton1, ui_event_SendButton, LV_EVENT_SHORT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SendButton2, ui_event_SendButton, LV_EVENT_SHORT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SendButton3, ui_event_SendButton, LV_EVENT_SHORT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SendButton4, ui_event_SendButton, LV_EVENT_SHORT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SendButton5, ui_event_SendButton, LV_EVENT_SHORT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SendButton6, ui_event_SendButton, LV_EVENT_SHORT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SendButton7, ui_event_SendButton, LV_EVENT_SHORT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ConfigButton, ui_event_ConfigButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardButton, ui_event_KeyboardButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Send_Screen, ui_event_Send_Screen, LV_EVENT_ALL, NULL);

}
